### PR TITLE
Change codebase to use ENU instead of NED

### PR DESCRIPTION
**Pull request by SijmenHuizenga**
In this pr I refactored the codebase to use the ENU coordinate frames as used in the autonomous industry. See the [ROS REP 103](https://www.ros.org/reps/rep-0103.html) and the [Automated Driving Toolbox](https://www.mathworks.com/help/driving/ug/coordinate-systems.html). This replaces the NED coordinate system introduced by using AirSim.

From now on we are using [the following coordinate system](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/pull/231/files#diff-d45885471513f592bc35897652eae75b) This introduces the following breaking change:

* **From now on, all coordinates in the settings.json should be in ENU with x forward** instead of NED with x forward. This relates to all x, y, z, roll, pitch, yaw and vertical & horizontal field of views. So flip the Z axis and flip the vertical field of view upper and lower.
* **From now on, yaw 0 means car facing east.** (in line with ros standard). Before, yaw 0 meant car facing north.

I've tested all the things I could think of that use coordinate's and rotations. This is what I have tested:

- [x] Odometry position
- [x] Odometry velocity
- [x] Odometry orientation
- [x] GPS
- [x] IMU Acceleration
- [x] IMU Orientation
- [x] IMU Angluar Velocity
- [x] Camera positioning and rotation from settings.json to output
- [x] Lidar positioning and rotation settings.json
- [x] Lidar points
- [x] ROS tf's
- [x] GSS
- [x] Track

### Can you help with testing?
It would be great if you could checkout this code, run it and see if your autonomous system still works. 
There should be no changes in the data coming out from the ros wrapper before and after this pr.

### CODE REVIEW

**Comment by SijmenHuizenga** [comment]
Lidar testing...

image

image

```
"LidarX": {
          "SensorType": 6,
          "Enabled": true,
          "X": 2, "Y": 0, "Z": 0.3,
          "Roll": 0, "Pitch": 0, "Yaw" : 0,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 10,
          "DrawDebugPoints": false
        },
        "LidarY": {
          "SensorType": 6,
          "Enabled": true,
          "X": 0, "Y": 2, "Z": 0.3,
          "Roll": 0, "Pitch": 0, "Yaw" : 0,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 5,
          "DrawDebugPoints": false
        },
        "LidarZ": {
          "SensorType": 6,
          "Enabled": true,
          "X": 0, "Y": 0, "Z": 2,
          "Roll": 0, "Pitch": 0, "Yaw" : 0,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 5,
          "DrawDebugPoints": false
        },
        "LidarRoll": {
          "SensorType": 6,
          "Enabled": true,
          "X": 1, "Y": 1, "Z": 0.3,
          "Roll": 60, "Pitch": 0, "Yaw" : 0,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 5,
          "DrawDebugPoints": false
        },
        "LidarPitch": {
          "SensorType": 6,
          "Enabled": true,
          "X": 1, "Y": 2, "Z": 0.3,
          "Roll": 0, "Pitch": 60, "Yaw" : 0,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 5,
          "DrawDebugPoints": false
        },
        "LidarYaw": {
          "SensorType": 6,
          "Enabled": true,
          "X": 1, "Y": 3, "Z": 0.3,
          "Roll": 0, "Pitch": 0, "Yaw" : 60,
          "NumberOfLasers": 4,
          "PointsPerScan": 4096,
          "VerticalFOVUpper": 5,
          "VerticalFOVLower": -5,
          "HorizontalFOVStart": -90,
          "HorizontalFOVEnd": 90,
          "RotationsPerSecond": 5,
          "DrawDebugPoints": false
        },
```

Success!

**Comment by davidoort** [comment]
image
This is with the same settings.json we used in competition. This is not an issue with this PR, it's just that during competition the sensors had to be placed in NED coordinates in the settings.json file. I hope this has been clearly stated somewhere.

**Comment by davidoort** [comment]
- Autonomous driving with groundtruth track and odometry works

- Autonomous driving with only groundtruth track does not work. Still don't know why but it has to be an issue with either gps, gss or IMU

**Review by davidoort — CHANGES_REQUESTED** [review]
image

At the moment I can't drive autonomously with the same software stack as the one in FSOnline, so we should figure out what is going on before merging. In the picture you can see the estimated car pos vs the groundtruth car pos. During competition they were on top of each other

**Comment by davidoort** [comment]
After flipping the sign of Z for the lidar and of VerticalFOVLower in the settings.json file I get a pointcloud that is equal or resembles our original one
image

**Comment by SijmenHuizenga** [comment]
@davidoort Thanks you so much for testing!

I ran some more system identification tests to validate the correctness of imu, gps and gss. I manually drove the car in a certain pattern and plotted all the things. 

**On master**
image

**On this branch**

image

**Comment by davidoort** [comment]
> @davidoort Thanks you so much for testing!
> 
> I ran some more system identification tests to validate the correctness of imu, gps and gss. I manually drove the car in a certain pattern and plotted all the things.
> 
> **On master**
> image
> 
> **On this branch**
> 
> image

Cool! It seems like gps longitude is flipped right? that would certainly explain the issue I'm having

**Comment by SijmenHuizenga** [comment]
Yes it does!

**Review by davidoort — APPROVED** [review]
Adjusting the initial heading of the car in our Kalman filter from North to East and flipping the z signs and pitch angle signs in our settings.json worked!

**Pull request merged**
