### PR TITLE
Added big orange cones to testing_only track

### PR DESCRIPTION
**Pull request by wouter-heerwegh**
This is a solution for issue #254.

Probably not the cleanest way to do this, but I don't know much about unreal engine. Wanted to the same thing in the referee blueprint as was done with 'Track', but for some reason my reference to the start finish line never became anything else than 'None'.

### CODE REVIEW

**Review by SijmenHuizenga — APPROVED** [review]
Great work! Just tested it and it works smoothly and correctly. Don't worry about having less experience with Unreal, code and blueprints look perfectly fine as they are!

For future reference, this is the addition in the StartFinishLine construction blueprint:

image

This is the addition in the Referee blueprint:

image

**Comment by SijmenHuizenga** [comment]
Thanks a lot for this @wouter-heerwegh! Merging this now. 

Do you need a new release right away? If that's the case feel free to comment and I will create one.

**Comment by wouter-heerwegh** [comment]
I've recorded a rosbag with the change I applied, so it's not urgent. I do have a question about the lidar sensors though.

I was simulating one (32 layers) with a total of 32000+ points but there was a major distance between the pointcloud and the reference track. Is this solely due to the data being out of sync?

Also, is the pointcloud fully compensated for yaw, pitch and roll of the car?

**Comment by SijmenHuizenga** [comment]
Can the major distance difference be cause the different coordinate systems of the lidar and reference track? The lidar points are relative to the car while the reference track is relative to the world (that is, relative to some arbitrary point close to where the car starts).

All points in the pointcloud are relative to the car's position (x, y, z) and orientation (rol, pitch, yaw). So if the car pitches, the pointcloud does as well.

**Comment by wouter-heerwegh** [comment]
It's not due to the coordinate systems being different because they start equal and stay pretty accurate for a couple of meters. It's probably a combination of me not compensating for this yaw, pitch and roll, and everything taking too long to process.

**Pull request merged**
