### PR TITLE
Fix installation ubuntu20.04 22.04

### PR DESCRIPTION
**Pull request by RoyAmoyal**
I have included the necessary files along with a guide for installing and building the project from source on Ubuntu 20.04 and Ubuntu 22.04+.

### CODE REVIEW

**Comment by wouter-heerwegh** [comment]
Hi @RoyAmoyal,

Thanks for contributing. I quickly went over the changes and tried to simplify it a bit, by changing the regular `setup.sh` and `build.sh` files, so step 3 should no longer be required. Also, after building with the docker container, is step 6 needed? Are you not able to launch the project directly?

**Comment by RoyAmoyal** [comment]
> Hi @RoyAmoyal,
> 
> Thanks for contributing. I quickly went over the changes and tried to simplify it a bit, by changing the regular `setup.sh` and `build.sh` files, so step 3 should no longer be required. Also, after building with the docker container, is step 6 needed? Are you not able to launch the project directly?

Yes, unfortunately, you need to run the command in step 6 (only done once) to build the project with Unreal. I have tested twice on different computers.
After that, you can launch it normally. (This solution is also mentioned in #365 )

**Comment by RoyAmoyal** [comment]
> Hmm okay, would you be able to share the error logs when not using step 6 if you still have them? Is this where it complains about the `uint64_t`?
> 
> Other than that the changes look good to me.

Without running step 6, even with the modified setup.sh/build.sh for Ubuntu 20.04/22.04, you'll still encounter the same error as in #365 : "Engine modules are out of date."

If you skip the modified setup.sh/build.sh but run step 6, the error will still occur.

You need both the modified setup.sh/build.sh and step 6 to successfully build the project with Unreal.

**Comment by wouter-heerwegh** [comment]
The modules should indeed be out of date, but when AirLib is correctly built, Unreal Engine should be able to build the AirLib module itself. If it doesn't and you get the message that you should build from source, than there should be some more information logged in the terminal you used to launch the project. I would assume it didn't work before because of the `pthread` symbols being available in the library, but with the docker container, it shouldn't contain them.

**Comment by RoyAmoyal** [comment]
I believe the issue is related to the default Unreal Editor build configuration. A team member in our team confirmed that he also encountered the error when trying to build the project with the default configuration or when attempting to open the .uproject file directly without using the command from step 6.

Step 6 provides a way to ensure the correct build configuration (e.g., Development mode and Linux platform). We should keep this in the documentation because anyone building from source will likely run into this error with the default configuration.

It's also solved #365.

**Comment by wouter-heerwegh** [comment]
I'm asking, because we didn't run into this issue back on Ubuntu 18.04, and I remember when I initially ran into this issue, that it might be that the executable does not work for every system. But should be okay, for general releases I will just use Windows anyway.

I'm going to change the the documentation slightly, since the changes only impact the way AirSim should be built.

**Comment by wouter-heerwegh** [comment]
Hi @RoyAmoyal,

What are your thoughts on the last changes to the documentation?

**Review by wouter-heerwegh — APPROVED** [review]
Okay, looks good to me then, let's merge it.

**Pull request merged**
