### PR TITLE
Fix brakes not working

### PR DESCRIPTION
**Pull request by mateusz-lichota**
The reverse as brake field on the vehicle pawn must be unchecked
for brakes to work, this PR does just that

Before, the properties of the vehicles were overwritten in code by airsim, so this setting didn't actually change anything, but since #312 removed that, the brakes stopped working

### CODE REVIEW

**Comment by wouter-heerwegh** [comment]
@b1n-ch1kn, @mateusz-lichota, this means that the drifting is intentional. Should we in your opinion use the settings from unreal engine? Or keep the ones that are in there now?

**Review by wouter-heerwegh — APPROVED** [review]

**Comment by mateusz-lichota** [comment]
The drifting might look cool, but it also makes it impossible for the autonomous system to engage the brakes, so we definitely need this PR to reintroduce previous behavior

**Comment by b1n-ch1kn** [comment]
Would the drifting be something that could be per-car? Our car is 4WD which has insane grip, so if I ever get our car model working, I'd try to remove it for a bit more realistic driving. 
Also, we currently use the reverse throttle so we can run a remote keyboard control without restarting the bridge in manual mode, so I'd test if that still works. https://github.com/QUT-Motorsport/Formula-Student-Driverless-Simulator/commit/35171f92ae04792c15793364f477c9f2e6ce7c22

**Comment by wouter-heerwegh** [comment]
@mateusz-lichota It currently happens a lot more on keyboard. I checked with a controller and I can accelerate without drifting. When going a bit faster it is hard to control. I think we should supply both blueprints (stable and drifting) as some teams might try to play with both. For the competition, however, I think it is best to stick with 1 car with stable settings (as it is easier).

@b1n-ch1kn they are on a per car basis as for the ADS vehicle it happens way less. It could be interesting to see what setting that was deleted is causing the cars now to spin though

**Comment by mateusz-lichota** [comment]
It's not hard to test which settings caused the change - you can look at what settings the code was overriding, set those on the vehicle pawn and drive it around. My guess would be that the Technion car has a huuuge torque limit set up, and that is causing the wheels to instantly loose traction, while the ads dv only has like 300Nm

**Comment by b1n-ch1kn** [comment]
So, I played around with this merge. In the UE editor/play windows i'm able to use the brake, but exporting to .exe removes brake functionality - both with an autonomous controller and keyboard input. I also re-ran build.cmd before exporting.

On a plus, I was able to play around with the Pawn kinematics to make it more akin to the original, so the drifting is gone.

**Pull request merged**
